name: "Pull Request Closed"

on:
  pull_request:
    types:
      - closed

concurrency:
  group: "pr-closed"
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  remove-pr-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          version: 22,
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install
